# Generated by Django 5.2.8 on 2025-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Залиште порожнім, якщо товар не на знижці', max_digits=10, null=True, verbose_name='Акційна ціна'),
        ),
    ]
